### ISSUE TITLE
Prefer Mixin Module to Base Class

### ISSUE THREAD

**Issue by yfeldblum** [thoughtbot/high_voltage#56]
Use a mixin module (`HighVoltage::ControllerMixin`) instead of a base class (`HighVoltage::PagesController`).

The base class can of course simply include the mixin module as its complete implementation for backwards compatibility:

```
class HighVoltage::PagesController
  include HighVoltage::ControllerMixin
  # that's all, folks!
end
```

There are projects without an `ApplicationController` class, or with a common controller base class named differently, or with multiple area-specific controller base classes.

**Comment by rromanchuk** [comment]
I was surprised too 

```ruby
 namespace :foo do
    get "/pages/*id" => 'pages#show', as: :page, format: false
  end

get "/pages/*id" => 'pages#show', as: :page, format: false
```

```ruby
module Foo
  class PagesController < Foo::ApplicationController
    include HighVoltage::StaticPage
  
  end
end
```

Given default content_path i would expect  `GET /foo/pages/about` to render `app/views/foo/pages/about.html.erb` just based on conventions.   I guess the easiest solution is to override  `def content_path`   https://github.com/thoughtbot/high_voltage/blob/main/lib/high_voltage/page_finder.rb#L21   

Hard coding the config content_path wouldn't work either because i still want `GET /pages/about` to work as normal

**Comment by rromanchuk** [comment]
This worked 

```ruby
module Foo
  class PagesController < Foo::ApplicationController
    include HighVoltage::StaticPage
  
    layout "foo/layouts/application"
    
    private
    def page_finder_factory
      DefaultPageFinder
    end
    
    class DefaultPageFinder < HighVoltage::PageFinder
      def content_path
        'foo/pages'
      end
    end
  end
end
```
